#include "main.h"

void SystemClock_Config(void);
static void MX_GPIO_Init(void);

void batHetDen();
void tatHetDen();
void sangTheoKimDongHo();
void tatTheoKimDongHo();
void sangTuTrongRaNgoai();


int main(void)
{
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  
  while (1)
  {
		batHetDen();
		HAL_Delay(500);
		sangTheoKimDongHo();
		HAL_Delay(500);
		tatHetDen();
		HAL_Delay(500);
		tatTheoKimDongHo();
		HAL_Delay(500);
		sangTuTrongRaNgoai();
		HAL_Delay(500);
		tatHetDen();
		HAL_Delay(500);
  }
  
}

void batHetDen(){
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_SET); // BAT DEN D1
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_SET); // BAT DEN D2
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET); // BAT DEN D3
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_SET); // BAT DEN D4
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_SET); // BAT DEN D5
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_SET); // BAT DEN D6
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_SET); // BAT DEN D7
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_SET); // BAT DEN D8
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_SET); // BAT DEN D9
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_SET); // BAT DEN D10
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_SET); // BAT DEN D11
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_SET); // BAT DEN D12
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_SET); // BAT DEN D13
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_SET); // BAT DEN D14
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_SET); // BAT DEN D15
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_SET); // BAT DEN D16
	
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_SET); // BAT DEN D17
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_SET); // BAT DEN D18
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_SET); // BAT DEN D19
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_SET); // BAT DEN D20
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_SET); // BAT DEN D21
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_SET); // BAT DEN D22
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_SET); // BAT DEN D23
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_SET); // BAT DEN D24
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_SET); // BAT DEN D25
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_SET); // BAT DEN D26
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_SET); // BAT DEN D27
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_SET); // BAT DEN D28
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_SET); // BAT DEN D29
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_SET); // BAT DEN D30
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_SET); // BAT DEN D31
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_SET); // BAT DEN D32
}

void tatHetDen() {
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_RESET); // TAT DEN D1
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_RESET); // TAT DEN D2
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET); // TAT DEN D3
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_RESET); // TAT DEN D4
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_RESET); // TAT DEN D5
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_RESET); // TAT DEN D6
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_RESET); // TAT DEN D7
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_RESET); // TAT DEN D8
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_RESET); // TAT DEN D9
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_RESET); // TAT DEN D10
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_RESET); // TAT DEN D11
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_RESET); // TAT DEN D12
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_RESET); // TAT DEN D13
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_RESET); // TAT DEN D14
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_RESET); // TAT DEN D15
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_RESET); // TAT DEN D16
	
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_RESET); // TAT DEN D17
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_RESET); // TAT DEN D18
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_RESET); // TAT DEN D19
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_RESET); // TAT DEN D20
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_RESET); // TAT DEN D21
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_RESET); // TAT DEN D22
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_RESET); // TAT DEN D23
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_RESET); // TAT DEN D24
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_RESET); // TAT DEN D25
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_RESET); // TAT DEN D26
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_RESET); // TAT DEN D27
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_RESET); // TAT DEN D28
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_RESET); // TAT DEN D29
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_RESET); // TAT DEN D30
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_RESET); // TAT DEN D31
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_RESET); // TAT DEN D32
}

void sangTheoKimDongHo(){
	tatHetDen();
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_SET); // BAT DEN D1
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_SET); // BAT DEN D2
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET); // BAT DEN D3
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_SET); // BAT DEN D4
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_SET); // BAT DEN D5
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_SET); // BAT DEN D6
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_SET); // BAT DEN D7
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_SET); // BAT DEN D8
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_SET); // BAT DEN D9
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_SET); // BAT DEN D10
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_SET); // BAT DEN D11
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_SET); // BAT DEN D12
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_SET); // BAT DEN D13
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_SET); // BAT DEN D14
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_SET); // BAT DEN D15
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_SET); // BAT DEN D16
	HAL_Delay(500);
	
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_SET); // BAT DEN D17
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_SET); // BAT DEN D18
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_SET); // BAT DEN D19
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_SET); // BAT DEN D20
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_SET); // BAT DEN D21
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_SET); // BAT DEN D22
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_SET); // BAT DEN D23
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_SET); // BAT DEN D24
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_SET); // BAT DEN D25
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_SET); // BAT DEN D26
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_SET); // BAT DEN D27
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_SET); // BAT DEN D28
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_SET); // BAT DEN D29
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_SET); // BAT DEN D30
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_SET); // BAT DEN D31
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_SET); // BAT DEN D32
	HAL_Delay(500);
}






void tatTheoKimDongHo(){
	batHetDen();
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_RESET); // TAT DEN D1
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_RESET); // TAT DEN D2
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET); // TAT DEN D3
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_RESET); // TAT DEN D4
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_RESET); // TAT DEN D5
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_RESET); // TAT DEN D6
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_RESET); // TAT DEN D7
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_RESET); // TAT DEN D8
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_RESET); // TAT DEN D9
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_RESET); // TAT DEN D10
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_RESET); // TAT DEN D11
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_RESET); // TAT DEN D12
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_RESET); // TAT DEN D13
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_RESET); // TAT DEN D14
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_RESET); // TAT DEN D15
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_RESET); // TAT DEN D16
	HAL_Delay(500);
	
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_RESET); // TAT DEN D17
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_RESET); // TAT DEN D18
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_RESET); // TAT DEN D19
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_RESET); // TAT DEN D20
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_RESET); // TAT DEN D21
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_RESET); // TAT DEN D22
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_RESET); // TAT DEN D23
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_RESET); // TAT DEN D24
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_RESET); // TAT DEN D25
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_RESET); // TAT DEN D26
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_RESET); // TAT DEN D27
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_RESET); // TAT DEN D28
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_RESET); // TAT DEN D29
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_RESET); // TAT DEN D30
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_RESET); // TAT DEN D31
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_RESET); // TAT DEN D32
	HAL_Delay(500);
}



void SystemClock_Config(void){
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);
  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    Error_Handler();
  }
}


void sangTuTrongRaNgoai(){
	tatHetDen();
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_SET); // BAT DEN D1
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_SET); // BAT DEN D2
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_SET); // BAT DEN D32
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET); // BAT DEN D3
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_SET); // BAT DEN D31
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_SET); // BAT DEN D4
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_SET); // BAT DEN D30
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_SET); // BAT DEN D5
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_SET); // BAT DEN D29
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_SET); // BAT DEN D6
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_SET); // BAT DEN D28
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_SET); // BAT DEN D7
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_SET); // BAT DEN D27
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_SET); // BAT DEN D8
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_SET); // BAT DEN D26
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_SET); // BAT DEN D9
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_SET); // BAT DEN D25
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_SET); // BAT DEN D10
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_SET); // BAT DEN D24
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_SET); // BAT DEN D11
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_SET); // BAT DEN D23
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_SET); // BAT DEN D12
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_SET); // BAT DEN D22
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_SET); // BAT DEN D13
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_SET); // BAT DEN D21
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_SET); // BAT DEN D14
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_SET); // BAT DEN D20
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_SET); // BAT DEN D15
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_SET); // BAT DEN D19
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_SET); // BAT DEN D16
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_SET); // BAT DEN D18
	HAL_Delay(500);
	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_SET); // BAT DEN D17
}







/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOE_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5
                          |GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9
                          |GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13
                          |GPIO_PIN_14|GPIO_PIN_15|GPIO_PIN_0|GPIO_PIN_1, GPIO_PIN_RESET);

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11
                          |GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15
                          |GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3
                          |GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7, GPIO_PIN_RESET);

  /*Configure GPIO pins : PE2 PE3 PE4 PE5
                           PE6 PE7 PE8 PE9
                           PE10 PE11 PE12 PE13
                           PE14 PE15 PE0 PE1 */
  GPIO_InitStruct.Pin = GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5
                          |GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9
                          |GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13
                          |GPIO_PIN_14|GPIO_PIN_15|GPIO_PIN_0|GPIO_PIN_1;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

  /*Configure GPIO pins : PD8 PD9 PD10 PD11
                           PD12 PD13 PD14 PD15
                           PD0 PD1 PD2 PD3
                           PD4 PD5 PD6 PD7 */
  GPIO_InitStruct.Pin = GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11
                          |GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15
                          |GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3
                          |GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);

}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
